### ISSUE TITLE
Determine technology stack

### ISSUE THREAD

**Issue by macrivello** [cpe308-309/AvengersRepo#11]
We should more or less finalize our core technology choices for the prototype.

**Comment by macrivello** [comment]
We have settled on Sprint Boot for our backend, React for the front end, and Postgres for our Database. 

Our toolchain is tracked here:
https://github.com/cpe308-309/AvengersRepo/blob/master/toolchain.txt

**Comment by m-duran** [comment]
Should we close this now or are we still deciding on something?

**Comment by macrivello** [comment]
The primary technology stack has been decided: Spring Boot, React, Postgres. I suspect we will be using Hibernate as our ORM. There will be a handful of other dependencies that we will need to pull in that are TBD, but the overall stack has been chosen. I'm going to close this one. Thanks @m-duran for following up on this.
