### ISSUE TITLE
Define SRS 3.2.5 Other non-functional requirements

### ISSUE THREAD

**Issue by BryceV** [cpe308-309/AvengersRepo#22]

**Comment by BryceV** [comment]
User reqs?: Here, you describe the services provided for the user. The nonfunctional system
requirements should also be described in this section. This description may use
natural language, diagrams, or other notations that are understandable to
customers. Product and process standards that must be followed should be
specified.

**Comment by m-duran** [comment]
I don't know what else to add here. If you can think of anything, add it.
