### ISSUE TITLE
Create Admin Class Object diagram

### ISSUE THREAD

**Issue by BryceV** [cpe308-309/AvengersRepo#37]

**Comment by macrivello** [comment]
Would this not just be a single object box as Catalog Admin? Or am I missing something here? The diagram should represent a runtime instance, correct? And all the parent classes are abstract.

**Comment by macrivello** [comment]
The single CatalogAdmin object would also show the inherited attributes.

**Comment by macrivello** [comment]
Its simple. but its here. https://drive.google.com/open?id=0B9F1DNYCrDCHb3lxeGozM2I5bjg 

Are the flowchart objects even necessary? And if so, should I the objects the flowchart contains?
