### ISSUE TITLE
Implement basic database structure for Vertical Prototype

### ISSUE THREAD

**Issue by m-duran** [cpe308-309/AvengersRepo#40]
Implement the base tables needed for the vertical prototype. 
The vertical prototype needs to be able to add a course entry to a particular flowchart. The course needs to come from a list of courses, not arbitrary data typed in by the user. 

Suggested tables: Course, Student, Flowchart, and FlowchartEntry

**Comment by JPautz** [comment]
Currently most of the way through, code is on postgres branch

**Comment by JPautz** [comment]
All Tables implemented, Objects mapped, and Services functional. Has been committed to the master branch.
