### ISSUE TITLE
Add data.sql to prepopulate database with Course and Quarter information. 

### ISSUE THREAD

**Issue by macrivello** [cpe308-309/AvengersRepo#47]

**Comment by macrivello** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html

**Comment by JPautz** [comment]
Found out how to do it, might be easier then using the dbloader, will continue to investigate.

**Comment by macrivello** [comment]
We'll be using the DBLoader.
