### ISSUE TITLE
Set up checkstyle to work with intellij

### ISSUE THREAD

**Issue by BryceV** [cpe308-309/AvengersRepo#78]

**Comment by BryceV** [comment]
General install process: 
1) Go to File>Settings>Plugins>Browse repositories and look for the Checkstyle-IDEA and download it.
2)Restart Intellij
3) Go to File>Settings>Other Settings>Checkstyle and select a configuration file (I did default for now)
4) Notice the Checkstyle button is now at the bottom left of your IDE. This will run with every code analyze but appears like it can be run separately

**Comment by BryceV** [comment]
Just comment when you have in installed and once everyone is good we can close this issue.

**Comment by JPautz** [comment]
Done, good instructions!

**Comment by mpjimenez** [comment]
Installed!

**Comment by BryceV** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

**Comment by macrivello** [comment]
Installed on my IDE.
